version: '3'

services:
  api:
    container_name: api
    build: 'api/.'
    restart: unless-stopped
    ports:
      - "8000:8000"
  app:
    container_name: app
    build: 'app/.'
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "5000:5000"
  nginx:
    container_name: nginx
    build: 'nginx/.'
    restart: always
    ports: 
      - "80:80"
  mysql:
    container_name: mysql
    build: 'mysql/.'
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
      container_name: phpmyadmin
      build: 'phpmyadmin/.'
      restart: unless-stopped
      links:
          - mysql
      depends_on:
          - mysql
      ports:
          - "8080:80"  
      environment:
          PMA_HOST: mysql

volumes:
  mysql-data:
    driver: local