version: '3'

services:
  api:
    container_name: api
    build: 'api/.'
    restart: unless-stopped
    ports:
      - "8000:8000"
  app:
    container_name: app
    build: 'app/.'
    restart: unless-stopped
    ports:
      - "5000:5000"
  nginx:
    container_name: nginx
    build: 'nginx/.'
    restart: always
    ports: 
      - "80:80"
